---
- name: Adding 6 GB of Memory to the chaos attack
  hosts: localhost

  tasks:

  - name: Adding 2 GB of Memory to the chaos attack
    script: gremlinMemoryAttack.sh
  - name: checking current state of attack 
    script: gremlinMemorystatusattack.sh  
  - debug:
      msg: echo to view graph 'https://grafana-openshift-monitoring.apps.ocppilot.ocpcontainer.com/d/fac67cfbe174d3ef53eb473d73d9212f/use-method-node?orgId=1&refresh=10s&var-datasource=prometheus&var-instance=ip-10-0-170-22.ec2.internal&from=1580932893751&to=1580936493752' 
